### ISSUE TITLE
Background image vs background color

### ISSUE THREAD

**Issue by stephenajulu** [themefisher/kross-jekyll-portfolio-template#1]
Hi how are you? I am a beginner to web development. I loved your design. I decided to use it for my site. Now i have a question, how can i change the background from color to image. I understand you decided to use purple. I want to use an image instead. Something that can work even on a mobile phone. Also another question. On mobile can i have 2 skills column instead of 1? Attached find my attempt to add, an image as a background image which failed terribly (on the desktop it seems to work but on mobilel not so much). Here is a link to my website: https://stephenajulu.com @mehedi-sharif @themefisher

Seems i cant attach, but just visit the link. Your prompt response and help will be much appreciated.

**Comment by developer-evan** [comment]
hey there, this theme is based on background-color. so you can't put background-image if you don't have knowledge on html, css, and jekyll.

You can contact us for any kind of customization at mehedi@themefisher.com (paid).
