### ISSUE TITLE
Experience section icons

### ISSUE THREAD

**Issue by moribots** [themefisher/kross-jekyll-portfolio-template#2]
If the experience icon (icon-1.png etc) images are replaced with a different image, they do not appear in the live site, but do appear in the localhost.

**Comment by themefisherDev** [comment]
I think you messed up capital letter and small letter in the image name or path.

**Comment by developer-evan** [comment]
Did you fix your problem? I am going to close this issue, if you have any more queries, don't hesitate to reopen this issue.
